name: terraform-apply

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-apply-dev
  cancel-in-progress: false

jobs:
  validate-and-security:
    uses: ./.github/workflows/terraform-ci.yml

  apply:
    needs: validate-and-security
    name: Terraform Apply (dev)
    runs-on: ubuntu-latest
    environment: dev
    env:
      TARGET_ENV: dev
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_service_api_key: ${{ secrets.TF_VAR_SERVICE_API_KEY }}
      TF_VAR_master_key: ${{ secrets.TF_VAR_MASTER_KEY }}
      TF_VAR_togglemaster_gitops_repo_url: ${{ vars.TOGGLEMASTER_GITOPS_REPO_URL }}
      TF_VAR_togglemaster_gitops_branch: ${{ vars.TOGGLEMASTER_GITOPS_BRANCH }}
      TF_VAR_togglemaster_addons_repo_url: ${{ vars.TOGGLEMASTER_ADDONS_REPO_URL }}
      TF_VAR_togglemaster_addons_branch: ${{ vars.TOGGLEMASTER_ADDONS_BRANCH }}
      TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
      TF_BACKEND_REGION: ${{ vars.TF_BACKEND_REGION }}
      TF_BACKEND_ROLE_ARN: ${{ vars.TF_BACKEND_ROLE_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Exportar variaveis sensiveis para Terraform
        run: bash .github/scripts/export-tfvars-env.sh

      - name: Renderizar backend config
        run: bash .github/scripts/render-backend-config.sh backend.hcl "${TARGET_ENV}"

      - name: Terraform init
        run: terraform init -backend-config=backend.hcl



      - name: Terraform plan
        run: terraform plan -var-file="environments/${TARGET_ENV}.tfvars" -out=tfplan

      - name: Terraform apply com plano salvo
        run: terraform apply -auto-approve tfplan
